//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EnviarFactura.FacturaElectronica {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FacturaSoap", Namespace="http://WebSites/FacturaCostaRica/")]
    public partial class Factura : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private UserDetails userDetailsValueField;
        
        private System.Threading.SendOrPostCallback RegistraXMLFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistraMensajeReceptorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFacturaEstadoFullOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFacturaEstadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Factura() {
            this.Url = global::EnviarFactura.Properties.Settings.Default.ConsoleApp1_FacturaElectronica_Factura;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserDetails UserDetailsValue {
            get {
                return this.userDetailsValueField;
            }
            set {
                this.userDetailsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistraXMLFacturaCompletedEventHandler RegistraXMLFacturaCompleted;
        
        /// <remarks/>
        public event RegistraMensajeReceptorCompletedEventHandler RegistraMensajeReceptorCompleted;
        
        /// <remarks/>
        public event GetFacturaEstadoFullCompletedEventHandler GetFacturaEstadoFullCompleted;
        
        /// <remarks/>
        public event GetFacturaEstadoCompletedEventHandler GetFacturaEstadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebSites/FacturaCostaRica/RegistraXMLFactura", RequestNamespace="http://WebSites/FacturaCostaRica/", ResponseNamespace="http://WebSites/FacturaCostaRica/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode RegistraXMLFactura(string xmlFactura, string secuenciaFacturaReferencia) {
            object[] results = this.Invoke("RegistraXMLFactura", new object[] {
                        xmlFactura,
                        secuenciaFacturaReferencia});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void RegistraXMLFacturaAsync(string xmlFactura, string secuenciaFacturaReferencia) {
            this.RegistraXMLFacturaAsync(xmlFactura, secuenciaFacturaReferencia, null);
        }
        
        /// <remarks/>
        public void RegistraXMLFacturaAsync(string xmlFactura, string secuenciaFacturaReferencia, object userState) {
            if ((this.RegistraXMLFacturaOperationCompleted == null)) {
                this.RegistraXMLFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistraXMLFacturaOperationCompleted);
            }
            this.InvokeAsync("RegistraXMLFactura", new object[] {
                        xmlFactura,
                        secuenciaFacturaReferencia}, this.RegistraXMLFacturaOperationCompleted, userState);
        }
        
        private void OnRegistraXMLFacturaOperationCompleted(object arg) {
            if ((this.RegistraXMLFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistraXMLFacturaCompleted(this, new RegistraXMLFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebSites/FacturaCostaRica/RegistraMensajeReceptor", RequestNamespace="http://WebSites/FacturaCostaRica/", ResponseNamespace="http://WebSites/FacturaCostaRica/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode RegistraMensajeReceptor(string xmlMensajeRespuesta, string tipoCedulaEmisor) {
            object[] results = this.Invoke("RegistraMensajeReceptor", new object[] {
                        xmlMensajeRespuesta,
                        tipoCedulaEmisor});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void RegistraMensajeReceptorAsync(string xmlMensajeRespuesta, string tipoCedulaEmisor) {
            this.RegistraMensajeReceptorAsync(xmlMensajeRespuesta, tipoCedulaEmisor, null);
        }
        
        /// <remarks/>
        public void RegistraMensajeReceptorAsync(string xmlMensajeRespuesta, string tipoCedulaEmisor, object userState) {
            if ((this.RegistraMensajeReceptorOperationCompleted == null)) {
                this.RegistraMensajeReceptorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistraMensajeReceptorOperationCompleted);
            }
            this.InvokeAsync("RegistraMensajeReceptor", new object[] {
                        xmlMensajeRespuesta,
                        tipoCedulaEmisor}, this.RegistraMensajeReceptorOperationCompleted, userState);
        }
        
        private void OnRegistraMensajeReceptorOperationCompleted(object arg) {
            if ((this.RegistraMensajeReceptorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistraMensajeReceptorCompleted(this, new RegistraMensajeReceptorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebSites/FacturaCostaRica/GetFacturaEstadoFull", RequestNamespace="http://WebSites/FacturaCostaRica/", ResponseNamespace="http://WebSites/FacturaCostaRica/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetFacturaEstadoFull(int idFactura) {
            object[] results = this.Invoke("GetFacturaEstadoFull", new object[] {
                        idFactura});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetFacturaEstadoFullAsync(int idFactura) {
            this.GetFacturaEstadoFullAsync(idFactura, null);
        }
        
        /// <remarks/>
        public void GetFacturaEstadoFullAsync(int idFactura, object userState) {
            if ((this.GetFacturaEstadoFullOperationCompleted == null)) {
                this.GetFacturaEstadoFullOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFacturaEstadoFullOperationCompleted);
            }
            this.InvokeAsync("GetFacturaEstadoFull", new object[] {
                        idFactura}, this.GetFacturaEstadoFullOperationCompleted, userState);
        }
        
        private void OnGetFacturaEstadoFullOperationCompleted(object arg) {
            if ((this.GetFacturaEstadoFullCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFacturaEstadoFullCompleted(this, new GetFacturaEstadoFullCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserDetailsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebSites/FacturaCostaRica/GetFacturaEstado", RequestNamespace="http://WebSites/FacturaCostaRica/", ResponseNamespace="http://WebSites/FacturaCostaRica/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetFacturaEstado(int idFactura) {
            object[] results = this.Invoke("GetFacturaEstado", new object[] {
                        idFactura});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetFacturaEstadoAsync(int idFactura) {
            this.GetFacturaEstadoAsync(idFactura, null);
        }
        
        /// <remarks/>
        public void GetFacturaEstadoAsync(int idFactura, object userState) {
            if ((this.GetFacturaEstadoOperationCompleted == null)) {
                this.GetFacturaEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFacturaEstadoOperationCompleted);
            }
            this.InvokeAsync("GetFacturaEstado", new object[] {
                        idFactura}, this.GetFacturaEstadoOperationCompleted, userState);
        }
        
        private void OnGetFacturaEstadoOperationCompleted(object arg) {
            if ((this.GetFacturaEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFacturaEstadoCompleted(this, new GetFacturaEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebSites/FacturaCostaRica/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://WebSites/FacturaCostaRica/", IsNullable=false)]
    public partial class UserDetails : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RegistraXMLFacturaCompletedEventHandler(object sender, RegistraXMLFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistraXMLFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistraXMLFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RegistraMensajeReceptorCompletedEventHandler(object sender, RegistraMensajeReceptorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistraMensajeReceptorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistraMensajeReceptorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetFacturaEstadoFullCompletedEventHandler(object sender, GetFacturaEstadoFullCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFacturaEstadoFullCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFacturaEstadoFullCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetFacturaEstadoCompletedEventHandler(object sender, GetFacturaEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFacturaEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFacturaEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591